# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/179MzLeJ9wnmqjJEB6wL8LsfwB6CqwqDM
"""

import time
import matplotlib.pyplot as plt
import random


def linear_search(arr, target):
    for i in range(len(arr)):
        if arr[i] == target:
            return i
    return -1

n_values = [100, 500, 1000, 5000, 10000, 50000]
times = []

for n in n_values:
    arr = [random.randint(0, n) for _ in range(n)]
    target = random.choice(arr)

    start_time = time.time()
    linear_search(arr, target)
    end_time = time.time()

    elapsed_time = end_time - start_time
    times.append(elapsed_time)


plt.plot(n_values, times, marker='o')
plt.title('Time Complexity of Linear Search')
plt.xlabel('Number of Elements (n)')
plt.ylabel('Time Taken (seconds)')
plt.grid(True)
plt.show()